export const RARITY_COLOR: Record<string, string> = {
  Basic: 'bg-slate-600',
  Common: 'bg-stone-500',
  Uncommon: 'bg-green-700',
  Rare: 'bg-blue-700',
  Epic: 'bg-purple-700',
  Legendary: 'bg-amber-600',
  Mythic: 'bg-red-700',
};

export const RARITY_TEXT: Record<string, string> = {
  Basic: 'text-slate-300',
  Common: 'text-stone-300',
  Uncommon: 'text-green-300',
  Rare: 'text-blue-300',
  Epic: 'text-purple-300',
  Legendary: 'text-amber-300',
  Mythic: 'text-red-300',
};

export const RARITY_ORDER: Record<string, number> = {
  Basic: 0,
  Common: 1,
  Uncommon: 2,
  Rare: 3,
  Epic: 4,
  Legendary: 5,
  Mythic: 6,
};

export const RARITY_HEX: Record<string, string> = {
  Basic: '#64748b',
  Common: '#78716c',
  Uncommon: '#16a34a',
  Rare: '#2563eb',
  Epic: '#7c3aed',
  Legendary: '#d97706',
  Mythic: '#dc2626',
};

export const STAT_LABEL: Record<string, string> = {
  pac: 'Pace',
  sho: 'Shooting',
  pas: 'Passing',
  dri: 'Dribbling',
  def: 'Defending',
  phy: 'Physicality',
  acceleration: 'Acceleration',
  sprint_speed: 'Sprint Speed',
  finishing: 'Finishing',
  shot_power: 'Shot Power',
  long_shots: 'Long Shots',
  penalties: 'Penalties',
  weak_foot: 'Weak Foot',
  attacking_iq: 'Attacking IQ',
  ground_pass: 'Ground Pass',
  lofted_pass: 'Lofted Pass',
  through_pass: 'Through Pass',
  crossing: 'Crossing',
  curve: 'Curve',
  free_kick_accuracy: 'FK Accuracy',
  sprint_dribbling: 'Sprint Drib.',
  close_dribbling: 'Close Drib.',
  skills: 'Skills',
  agility: 'Agility',
  balance: 'Balance',
  first_touch: 'First Touch',
  defensive_iq: 'Def. IQ',
  stand_tackle: 'Stand Tackle',
  slide_tackle: 'Slide Tackle',
  jockeying: 'Jockeying',
  interceptions: 'Interceptions',
  blocking: 'Blocking',
  strength: 'Strength',
  aggression: 'Aggression',
  stamina: 'Stamina',
  heading: 'Heading',
  jumping: 'Jumping',
  div: 'Diving',
  reflexes: 'Reflexes',
  positioning: 'Positioning',
  catching: 'Catching',
  parrying: 'Parrying',
  rushing: 'Rushing',
  command_of_area: 'Command Area',
  penalty_saving: 'Penalty Save',
  throwing: 'Throwing',
  kicking_power: 'Kicking Power',
};

export const POSITION_COLORS: Record<string, string> = {
  GK: 'bg-yellow-600',
  CB: 'bg-blue-700',
  FB: 'bg-blue-600',
  WB: 'bg-blue-500',
  DM: 'bg-green-700',
  CM: 'bg-green-600',
  AM: 'bg-green-500',
  WM: 'bg-green-500',
  ST: 'bg-red-600',
  WF: 'bg-red-500',
  CF: 'bg-red-500',
};
